#!/usr/bin/env python3
"""The 3x5 font and the 7x7 suit glyphs for asm/blackjack.tal, as pictures.

The .tal needs these as hex, and a hex table nobody can read is a hex table
nobody can check. So the glyphs are written here as ASCII, rendered here so they
can be looked at, and emitted as the DB lines the source wants. Run it with no
arguments to print the pictures, or --emit to get the assembler lines.

Usage:
    tools/bjfont.py            every glyph, as ASCII
    tools/bjfont.py --emit     DB lines for asm/blackjack.tal
"""

import sys

W, H = 3, 5

# One string per glyph, row by row. '#' is a lit pixel.
FONT_SRC = {
    'A': '.#./#.#/###/#.#/#.#',
    'B': '##./#.#/##./#.#/##.',
    'C': '.##/#../#../#../.##',
    'D': '##./#.#/#.#/#.#/##.',
    'E': '###/#../##./#../###',
    'F': '###/#../##./#../#..',
    'G': '.##/#../#.#/#.#/.##',
    'H': '#.#/#.#/###/#.#/#.#',
    'I': '###/.#./.#./.#./###',
    'J': '..#/..#/..#/#.#/.#.',
    'K': '#.#/#.#/##./#.#/#.#',
    'L': '#../#../#../#../###',
    'M': '#.#/###/#.#/#.#/#.#',
    'N': '#.#/###/###/#.#/#.#',
    'O': '.#./#.#/#.#/#.#/.#.',
    'P': '##./#.#/##./#../#..',
    'Q': '.#./#.#/#.#/###/.##',
    'R': '##./#.#/##./#.#/#.#',
    'S': '.##/#../.#./..#/##.',
    'T': '###/.#./.#./.#./.#.',
    'U': '#.#/#.#/#.#/#.#/.#.',
    'V': '#.#/#.#/#.#/.#./.#.',
    'W': '#.#/#.#/#.#/###/#.#',
    'X': '#.#/.#./.#./#.#/#.#',
    'Y': '#.#/#.#/.#./.#./.#.',
    'Z': '###/..#/.#./#../###',
    '0': '###/#.#/#.#/#.#/###',
    '1': '.#./##./.#./.#./###',
    '2': '##./..#/.#./#../###',
    '3': '###/..#/.##/..#/###',
    '4': '#.#/#.#/###/..#/..#',
    '5': '###/#../##./..#/##.',
    '6': '.##/#../###/#.#/###',
    '7': '###/..#/.#./#../#..',
    '8': '###/#.#/###/#.#/###',
    '9': '###/#.#/###/..#/##.',
    ' ': '.../.../.../.../...',
    ':': '.../.#./.../.#./...',
    '-': '.../.../###/.../...',
    '/': '..#/..#/.#./#../#..',
}

# The four suits, 7x7. Heart and spade are vertical mirrors, as they are on a
# real card; that is not a copy-paste of the hex, it is what the shapes are.
SUIT_SRC = {
    'S': '...#.../..###../.#####./#######/.##.##./..###../...#...',
    'H': '.##.##./#######/#######/#######/.#####./..###../...#...',
    'D': '...#.../..###../.#####./#######/.#####./..###../...#...',
    'C': '..###../.#####./..###../#######/..###../...#.../...#...',
}


def parse(src, w, h):
    rows = src.split('/')
    if len(rows) != h or any(len(r) != w for r in rows):
        raise ValueError('%r is not %dx%d' % (src, w, h))
    return rows


def glyph(src):
    return parse(src, W, H)


def suit(name):
    return parse(SUIT_SRC[name], 7, 7)


def font_bytes():
    """Every code point from 32 (space) to 90 ('Z'), column major, three bytes a
    glyph: each byte is one column, bit r of it being row r. Drawing a column is
    then one byte shifted by the row, which is what the ROM does - a row-major
    table would need a bit out of three different bytes for every pixel.

    Indexed by code - 32, so the ROM subtracts once and indexes. The codes with
    no glyph - the punctuation between 'Z' and 'a' - are blank slots, and there
    are 23 of them, which is the price of not needing a search. A lookup that
    skipped them would be shorter in the table and longer in the code."""
    out = {}
    for code in range(32, 91):
        ch = chr(code)
        src = FONT_SRC.get(ch, '.../.../.../.../...')
        rows = glyph(src)
        cols = []
        for x in range(W):
            b = 0
            for y in range(H):
                if rows[y][x] == '#':
                    b |= 1 << y
            cols.append(b)
        out[code] = cols
    return out


def suit_bytes():
    out = {}
    for name, src in SUIT_SRC.items():
        rows = suit(name)
        cols = []
        for x in range(7):
            b = 0
            for y in range(7):
                if rows[y][x] == '#':
                    b |= 1 << y
            cols.append(b)
        out[name] = cols
    return out


def main():
    a = sys.argv[1:]
    if '--emit' in a:
        fb, sb = font_bytes(), suit_bytes()
        print('; the 3x5 font, one glyph every three bytes, column major')
        print('; generated by tools/bjfont.py - edit the pictures there, not here')
        print('@font')
        for code in sorted(fb):
            c = fb[code]
            print('        DB $%02x, $%02x, $%02x        ; %d %s'
                  % (c[0], c[1], c[2], code,
                     repr(chr(code))[1:-1] if chr(code) in FONT_SRC else 'blank'))
        print('; the four suits, 7x7, same packing')
        print('@suits')
        for n in sorted(sb):
            c = sb[n]
            print('        DB ' + ', '.join('$%02x' % v for v in c)
                  + '        ; %s' % n)
        return

    fb = font_bytes()
    print('the 3x5 font, as pictures (blank slots skipped):')
    shown = [c for c in sorted(fb) if chr(c) in FONT_SRC]
    for start in range(0, len(shown), 12):
        chunk = shown[start:start + 12]
        print('  ' + ' '.join(('  ' if c == 32 else ' %s ' % chr(c)) for c in chunk))
        for y in range(H):
            print('  ' + '   '.join(
                ''.join('#' if fb[c][x] >> y & 1 else '.' for x in range(W))
                for c in chunk))
        print()
    print('the suits, 7x7:')
    names = sorted(SUIT_SRC)
    for y in range(7):
        print('  ' + '   '.join(''.join('#' if r[y][x] == '#' else '.'
                                        for x in range(7))
                                for r in (suit(n) for n in names)))
    print('  ' + '   '.join(' %s ' % n for n in names))
    print()
    print('%d slots (%d drawn), %d bytes; %d suits, %d bytes'
          % (len(fb), len(shown), len(fb) * 3, len(SUIT_SRC), len(SUIT_SRC) * 7))


if __name__ == '__main__':
    main()